# Generated by Django 5.2.5 on 2025-08-26 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_posts_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_uplaods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='pics/')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(upload_to='pics/'),
        ),
    ]
