# Generated by Django 5.2.5 on 2025-08-26 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_user_uplaods_alter_post_img'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_uplaods',
            new_name='user_uploads',
        ),
    ]
